<?php
namespace Wangjian\FrequencyLimit\Test;

use Wangjian\FrequencyLimit\MinuteGuard;

class MinuteGuardTest extends BaseTestCase
{
    public function testPass()
    {
        $guard = new MinuteGuard($this->client, 1);
        $this->assertEquals(true, $guard->pass('test'));
    }

    public function testFail()
    {
        $guard = new MinuteGuard($this->client, 0);
        $this->assertEquals(false, $guard->pass('test'));
    }

    public function testRecover()
    {
        $guard = new MinuteGuard($this->client, 1);
        $this->assertEquals(true, $guard->pass('test'));
        sleep(61);
        $this->assertEquals(true, $guard->pass('test'));
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->client->flushdb();
    }
}